language: python
python:
  - "3.4"
  - "3.5"
  - "pypy3"

install:
  - pip install --editable .
  - pip install coveralls
  - pip install pytest pytest-cov

script: make test

after_success:
  coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/18a32845ab49f23362e7
    on_success: change
    on_failure: always
    on_start: never